runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: blog.app

- url: /images
  static_dir: images


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"
